### ISSUE TITLE
How to generate GLONASS signals？

### ISSUE THREAD

**Issue by Gerald0217** [harshadms/galileo-sdr-sim#2]
Dear expert,

The specific query I have is: How to generate GLONASS signals? I am interested in understanding the technical aspects and processes involved in generating signals for GLONASS navigation.

If you could spare some time to share your expertise on this matter, I would greatly appreciate it. Any resources, references, or guidance you can provide will be immensely helpful.

Thank you very much for considering my inquiry. I look forward to hearing from you.

Best regards,

**Comment by harshadms** [comment]
Hi! You can refer to a document like this one to understand the signal and message structure. https://www.unavco.org/help/glossary/docs/ICD_GLONASS_4.0_(1998)_en.pdf

Cheers

**Comment by Gerald0217** [comment]
> Hi! You can refer to a document like this one to understand the signal and message structure. https://www.unavco.org/help/glossary/docs/ICD_GLONASS_4.0_(1998)_en.pdf
> 
> Cheers

Dear expert,

"Thank you for the advice given by the expert. Did the expert simulate the GLONASS signals through this document? Just seeking confirmation to gain confidence in the implementation. Thanks again for the expert's assistance."

Best regards,
