### ISSUE TITLE
Whete to get GAL ephemerides RINEX navigation file 

### ISSUE THREAD

**Issue by JakubSteiner** [harshadms/galileo-sdr-sim#4]
Sorry, for this rather trivial question. Where do you download the GAL ephemerides RINEX navigation file? For the gps-sdr-sim I download the file from https://cddis.nasa.gov/archive/gnss/data/daily/ but your SW uses a different format, right? Do you transform the .24n into .rnx or download the rinex file from a different website? 

Thank you. 
I really appreciate the work you have done with this SW.

**Comment by harshadms** [comment]
That's the correct place to get the rinex file. The extension doesn't matter as long as it's in RINEX3 format.
