### ISSUE TITLE
INAV message generation issues

### ISSUE THREAD

**Issue by MichalPf** [harshadms/galileo-sdr-sim#6]
First of all, thanks for this great project.
It seems, there are few bugs concerning the generation of the I/NAV data message though...
1) CRC seems to be wrong
a) There is one obvious bug when the offset is not incremented after the Even/Odd and Page Type bits are inserted to the middle of the page. CRC field is then 2 bits early.
b) The CRC computation algorimth is probably wrong. E.g., BitStream is handled like an array of nav message bytes, but each field is filled with a single bit. Also important to note that the GNSS usage of the CRC24Q usually includes the message lengths which are non-integer multiplies of the full bytes (i.e. there are some leftover bits which need a special care after the last full byte). Also when you want to get the correct signature, it seems that you need to let the algorithm process the crc result register three more times with the zero input byte (size of the CRC signature).

2) There is a bug in generation of I/NAV Word Type 5 ... there should be 23 spare bits at the end, not 3. This causes the rest of the message including the CRC field shifted 20 bits to the left.

3) There is probably still something else fishy somewhere since both ublox and GSRx show the position several meters to several tens of meters off.

**Comment by harshadms** [comment]
Hi! Thanks a lot for pointing out these issues. Sorry for a super late response, I had to take care of some other things. I'll try to look into these. If you have time it would be extremely helpful if you could contribute by correcting the CRC function.

**Comment by harshadms** [comment]
Hey! Appreciate the fixes. Thanks again :)
